site:
    owner:
        disque-shortname: icpc-cs-illinois-edu
comments: true

name: ACM@UIUC ICPC
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

future: false
